# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6e52d624398d209b92a3e7441e58d8bffc22fa19154e95935777685ebdda8d6329ca4f5e70b796c2242de7a844710fe8acb350e47add918c4e25a4adc2ef76e

test:
  secret_key_base: 67866ae37eedf9624b78273ce421c782d80bbf38bffcc7dd16e17cc2a62821a09170f667ef828662ad29a523ab49d6123e90f479b4afe6a8b014bf7c7d87371b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
